### PR TITLE
Created trundler report template

### PR DESCRIPTION
**Pull request by Matt-dD**

### CODE REVIEW

**Comment by datawookie** [comment]
This is looking good, @Matt-dD. Two quick comments:

1. We need to bring this to the user's attention, otherwise they won't know that it's there. So you need to mention it in the `README.md` file.
2. Unless there's a really good reason to, we generally would not include the HTML file as well as the Rmd, because the former is an artifact (which can be generated from the latter). Does that make sense? Anything that can be generated in code will normally not be stashed in the repository.

**Comment by Matt-dD** [comment]
@datawookie not sure how this slipped off my radar.  Sorry.  I have resolved those two issues above now.

**Comment by datawookie** [comment]
@Matt-dD this looks really good.

Have you tested installing the package directly from your branch and then checking to see whether the template shows up in the menu? Sorry, I would check but have no time now. :(

**Comment by Matt-dD** [comment]
@datawookie yes, it works when installed from my branch, but I had to restart RStudio before it showed up in the menu.

**Comment by datawookie** [comment]
:+1: Cool. Just added that useful nugget to the instructions. Merging.

**Comment by Matt-dD** [comment]
@datawookie ah yes, that would be important... thanks for adding that.

**Pull request merged**
